### ISSUE TITLE
`null` not accepted as value for `/domain/axes/x`

### ISSUE THREAD

**Issue by lewismc** [covjson/playground#13]
When I attempt to render [SPURS_wg_ASL2.nc.covjson](https://opendap.jpl.nasa.gov/opendap/OceanCirculation/insitu/L2/spurs1/waveglider/SPURS_wg_ASL2.nc.covjson) in the playground and after I [fix the current syntax issues](https://github.com/OPENDAP/bes/issues/650) I get the following errors
![Screen Shot 2022-06-23 at 8 48 51 AM](https://user-images.githubusercontent.com/1165719/175344482-36c16ad5-edf2-4af7-92a8-d5590df12ff6.png)

**Comment by lewismc** [comment]
This zip attachment, when unzipped includes the syntax-compliant covjson response.

[SPURS_wg_ASL2.nc.covjson.zip](https://github.com/covjson/playground/files/8968947/SPURS_wg_ASL2.nc.covjson.zip)

**Comment by jonblower** [comment]
Hi @lewismc, the error you're getting is saying that axis values must be unique. This is enforced by the [schema](https://github.com/covjson/covjson-validator/blob/main/schemas/valuesAxisBase.json), which is generating the error message you are seeing.

The [spec](https://opengeospatial.github.io/ogcna-auto-review/21-069.html#toc19) has the constraint that axis values must be monotonically increasing or decreasing (which disallows both null values and duplicates).

Is there a reason your axis has null values and duplicates? This is not usual.

**Comment by letmaik** [comment]
Closing this as it's working as expected. @lewismc Feel free to open an issue in https://github.com/opengeospatial/CoverageJSON if you have further questions on the spec.
